##' Ensure Imputation Inputs
##' 
##' @param data The data.frame containing the data to be imputed.
##' @param imputationParameters A list of the imputation parameters, such as
##' one generated by defaultImputationParameters().
##' 
##' @return No value is returned, but errors are thrown if the input parameters
##' are not as expected.
##' 

ensureImputationInputs = function(data, imputationParameters){
    
    ############################# Param checks #############################
    
    ### Check types of imputation parameters
    p = imputationParameters
    stopifnot(is.character(c(p$yearValue, p$byKey)))
    stopifnot(is(p$ensembleModels, "list"))
    stopifnot(sapply(p$ensembleModels, is) == "ensembleModel")
    stopifnot(is.logical(c(p$restrictWeights, p$plotImputation)))
    stopifnot(is.numeric(p$groupCount))
    stopifnot(is.character(c(p$missingFlag, p$imputationFlag,
                             p$newMethodFlag)))
    
    ### Check certain input parameters match allowable categories
    stopifnot(p$variable %in% c("production", "yield", "seed"))
    stopifnot(p$maximumWeights <= 1 & p$maximumWeights >= 0.5)
    stopifnot(p$errorType %in% c("raw", "loocv"))
    stopifnot(p$groupCount >= 2)
    stopifnot(p$groupCount <= 100)
    
    ### Ensure the error function is non-negative and returns a single value
    f = p$errorFunction
    stopifnot(is(f, "function"))
    stopifnot(f(1:10) >= 0)
    stopifnot(f(-1:-10) >= 0)
    stopifnot(length(f(1:10)) == 1)
    
    ############################# Data checks #############################
    
    ### Make sure all column name variables exist in data
    columnNames = c(p$imputationValueColumn,
                    p$imputationFlagColumn,
                    p$imputationMethodColumn,
                    p$yearValue,
                    p$byKey)
    missingColumns = ! columnNames %in% colnames(data)
    if( any(missingColumns) )
        stop("The following columns do not exist in data but should (or the ",
             "names in imputationParameters should be corrected):\n\t",
             paste(columnNames[missingColumns], collapse="\n\t"))
    
    ### Coerce columns to appropriate type:
    for(name in c(p$imputationValueColumn)){
        expr = substitute(x := as.numeric(data[[x]]), list(x = name))
        data[, eval(expr)]
    }
    for(name in c(p$imputationFlagColumn, p$imputationMethodColumn)){
        expr = substitute(x := as.character(data[[x]]), list(x = name))
        data[, eval(expr)]
    }

    ############################# Flag checks #############################
    
    ### Flag Table checks
    stopifnot(c(p$missingFlag, p$imputationFlag) %in%
                  p$flagTable$flagObservationStatus)
    stopifnot(is.data.frame(p$flagTable))
    stopifnot(colnames(p$flagTable) == c("flagObservationStatus",
                                         "flagObservationWeights"))
    stopifnot(is.character(p$flagTable$flagObservationStatus))
    stopifnot(is.numeric(p$flagTable$flagObservationWeights))
    stopifnot(p$flagTable$flagObservationWeights <= 1)
    stopifnot(p$flagTable$flagObservationWeights >= 0)
    
    ## Check that all flags are in the flagTable:
    flags = data[[p$imputationFlagColumn]]
    flags = unique(flags)
    missingFlags = flags[!flags %in% p$flagTable$flagObservationStatus]
    if(length(missingFlags) > 0){
        stop("Some observation flags are not in the flag table!  Missing:\n",
             paste0("'", missingFlags, "'", collapse="\n"))
    }
    
    ## Ensure flags of flagTable are valid
    stopifnot(checkObservationFlag(p$flagTable[["flagObservationStatus"]]))
    
    ### Globally assign ensuredImputationData so data will not need to be ensured again
    ensuredImputationData <<- TRUE
}