##' Ensure Processing Parameters are Valid
##' 
##' @param parameterList A list of the processing parameters, such as one
##' generated by defaultProcessingParameters().
##' 
##' @return No value is returned, but errors are thrown if the input parameters
##' are not as expected.
##' 

ensureProcessingParameters = function(parameterList){
    p = parameterList
    stopifnot(is.character(c(p$productionValue, p$productionObservationFlag,
                             p$productionMethodFlag, p$yieldValue,
                             p$yieldObservationFlag, p$yieldMethodFlag,
                             p$areaHarvestedValue,
                             p$areaHarvestedObservationFlag,
                             p$areaHarvestedMethodFlag, p$yearValue, p$byKey)))
    stopifnot(is.logical(c(p$removePriorImputation, p$removeConflictValues)))
    stopifnot(is.character(c(p$imputedFlag, p$naFlag,
                             p$newMethodFlag)))
}