##' Ensure Imputation Parameters are Valid
##' 
##' @param parameterList A list of the imputation parameters, such as one
##' generated by defaultImputationParameters().
##' 
##' @return No value is returned, but errors are thrown if the input parameters
##' are not as expected.
##' 

ensureImputationParameters = function(imputationParameters){
    p = imputationParameters
    stopifnot(is.character(c(p$yearValue, p$byKey)))
    stopifnot(p$variable %in% c("production", "yield", "seed"))
    stopifnot(is(p$ensembleModels, "list"))
    stopifnot(sapply(p$ensembleModels, is) == "ensembleModel")
    stopifnot(is.logical(c(p$restrictWeights, p$plotImputation)))
    stopifnot(p$maximumWeights <= 1 & p$maximumWeights >= 0.5)
    stopifnot(p$errorType %in% c("raw", "loocv"))
    f = p$errorFunction
    # Ensure the error function is non-negative and returns a single value
    stopifnot(is(f, "function"))
    stopifnot(f(1:10) >= 0)
    stopifnot(f(-1:-10) >= 0)
    stopifnot(length(f(1:10)) == 1)
    stopifnot(is.numeric(p$groupCount))
    stopifnot(p$groupCount >= 2)
    stopifnot(p$groupCount <= 100)
    stopifnot(is.character(c(p$missingFlag, p$imputationFlag,
                             p$newMethodFlag)))
    # Flag Table checks
    stopifnot(c(p$missingFlag, p$imputationFlag) %in%
                  p$flagTable$flagObservationStatus)
    stopifnot(is.data.frame(p$flagTable))
    stopifnot(colnames(p$flagTable) == c("flagObservationStatus",
                                         "flagObservationWeights"))
    stopifnot(is.character(p$flagTable$flagObservationStatus))
    stopifnot(is.numeric(p$flagTable$flagObservationWeights))
    stopifnot(p$flagTable$flagObservationWeights <= 1)
    stopifnot(p$flagTable$flagObservationWeights >= 0)
}